skip tombstone when iter rangelist
gimli-rs/gimli pull request #630
Opened 2022-10-26 03:44 UTC by shuoli84

fixes #629 
I add the check and skip logic between raw range => range, all tests passed, but dwarfdump tool is broken, because it expects one to one relationship between raw range and range. 
Any idea on how to fix this?

2022-10-26 03:55 UTC, shuoli84 commented
@philipc I fired a pr here, pls take a look?
There are different ways to solve the problem, my considerations:
1. add a flag on Range struct to indicate it is tombstone. But it will increase range size, which is over kill because tombstone is a rare case.
2. skip RawRange, which is wrong, RawRange is something raw I think?
3. keep RawRange, skips Range, which we have both the low level raw info and correct user facing behavior. 
So I implemented 3.

2022-10-26 04:24 UTC, philipc requested changes
I've noted a couple of things that needed fixing. However, I'm not sure yet that this is the approach we want to take. Another option would be to add a method to `Range` that checks if it is a tombstone.

For dwarfdump, there already isn't a one to one correspondence between `RawRange` and `Range`, so this would become an additional check. Having it as a method on `Range` might make that easier to implement.

I would also like to match LLVM's handling for DWARF v5 at the same time, since this will eventually become the DWARF v6 support. Trying to implement that might give a better feel for what the best approach is.

2022-10-26 04:24 UTC, philipc commented on src/read/rnglists.rs
> +                    self.base_address = try_tombstone!(addr);
A tombstone for a base address must not be ignored. Instead, all offsets using that base address are also tombstones. That is, change `add_base_address` to handle this for base addresses.

2022-10-26 04:24 UTC, philipc commented on src/read/rnglists.rs
> +                    let end = try_tombstone!(self.get_address(end)?);
Instead of checking this for each kind of entry, do a single check below at the same place we check `if range.begin > range.end`.

2022-10-26 04:46 UTC, shuoli84 commented
> I've noted a couple of things that needed fixing. However, I'm not sure yet that this is the approach we want to take. Another option would be to add a method to `Range` that checks if it is a tombstone.
>
> For dwarfdump, there already isn't a one to one correspondence between `RawRange` and `Range`, so this would become an additional check. Having it as a method on `Range` might make that easier to implement.

I think check against address is better compare to provide a method on `Range`, `Range` maybe created by Address calculation, if we didn't check against the Address, then tombstone + offset/length may produce valid address?
Or we do both, check against address, if it is tombstone, then create a Tombstone `Range`?

> I would also like to match LLVM's handling for DWARF v5 at the same time, since this will eventually become the DWARF v6 support. Trying to implement that might give a better feel for what the best approach is.

Do you mean how llvm handling tombstone address or something else? llvm skipped the tombstone range while parsing, I think it is same as what I did in this pr. ref: https://github.com/llvm/llvm-project/blob/2bdfececef4330b3a6489cdb67c57eb771d5f9e4/llvm/lib/DebugInfo/DWARF/DWARFDebugRangeList.cpp#L87

2022-10-26 05:00 UTC, philipc commented
> Range maybe created by Address calculation, if we didn't check against the Address, then tombstone + offset/length may produce valid address?

This should be handled in `add_base_address`.

> Do you mean how llvm handling tombstone address or something else?

I mean the DWARF v5 handling: https://github.com/llvm/llvm-project/blob/2bdfececef4330b3a6489cdb67c57eb771d5f9e4/llvm/lib/DebugInfo/DWARF/DWARFDebugRnglists.cpp#L95

2022-10-26 05:08 UTC, shuoli84 commented
> > Range maybe created by Address calculation, if we didn't check against the Address, then tombstone + offset/length may produce valid address?
> 
> This should be handled in `add_base_address`.
> 
> > Do you mean how llvm handling tombstone address or something else?
> 
> I mean the DWARF v5 handling: https://github.com/llvm/llvm-project/blob/2bdfececef4330b3a6489cdb67c57eb771d5f9e4/llvm/lib/DebugInfo/DWARF/DWARFDebugRnglists.cpp#L95

Thanks, I didn't aware of this 🤣 .. So what I implemented is actually the dwarfv4 logic, and the link you provided is the v5 one? Is it a good idea to implement both? I think v4 is quite common.

2022-10-26 05:09 UTC, philipc commented
> Is it a good idea to implement both? I think v4 is quite common.

Yes, this crate aims to support both.

2022-10-26 08:03 UTC, shuoli84 commented on src/read/rnglists.rs
> +                    let begin = self.get_address(begin)?;
check before begin + length, if begin is tombstone, then it will overflow

2022-10-26 08:23 UTC, shuoli84 commented
@philipc I've updated the logic to handle both v4 and v5. 
Per dwarfdump. I think it is better to untie the `RawRange` and `Range`, maybe add a flag to control which set to show. I understand if add we add a method `is_tombstone` will make dwarfdump's logic easier, but that will leak the tombstone to end user. Also llvm's implementation just ignored the tombstone.

2022-10-26 10:45 UTC, shuoli84 commented
I made a simple change to print ranges first, then raw ranges second, seems not bad.

```
                    DW_AT_ranges                <rnglist at .debug_ranges+0x00000078 with 2 entries>
                        ranges:
                        [ 0] [00000004, 0000013b)
                        [ 1] [0000013c, 00000194)
                        raw ranges:
                        [ 0] <address pair low-off: 0x00000004 high-off: 0x0000013b>
                        [ 1] <address pair low-off: 0x0000013c high-off: 0x00000194>
```

2022-10-27 06:05 UTC, philipc commented
Thanks for working on this. I'm going to fix some things and experiment with alternatives. I'll open a new PR and add you as coauthor.

2022-10-27 06:47 UTC, closed without merging