Fix encoding of .eh_frame when the LSDA is encoded using a pointer sm…
gimli-rs/gimli pull request #704
Opened 2024-03-28 18:18 UTC by bjorn3

…aller than the address size

2024-03-28 18:20 UTC, bjorn3 commented
Without this an LSDA encoded as `DW_EH_PE_pcrel | DW_EH_PE_sdata4` would cause the `.eh_frame` section to be corrupt. I found this issue while implementing unwinding support for cg_clif.

2024-03-30 03:03 UTC, philipc requested changes
Thanks!

Can you add a test for this in `test_frame_table` (or change the test there to use `DW_EH_PE_sdata4`).

2024-03-30 09:02 UTC, bjorn3 commented
Done

2024-03-30 09:13 UTC, philipc approved these changes

2024-03-30 09:14 UTC, merged