Introduce new enum for `.dwo` section IDs
gimli-rs/gimli pull request #716
Opened 2024-05-24 10:17 UTC by jameysharp

Keeping this type distinct from the `SectionId` enum ensures that the compiler will report an error if someone adds incomplete support for new separate-debug sections.

As discussed in: https://github.com/gimli-rs/gimli/pull/714#discussion_r1611164319

The existing `SectionId::dwo_name` method did not match the list of sections actually supported elsewhere in gimli. I've added the one section ID that was missing (`.debug_macinfo.dwo`), but I have not removed the section IDs which are only present there: `.debug_str.dwo`, `.debug_cu_index`, and `.debug_tu_index`.

2024-05-24 11:10 UTC, philipc requested changes
Sorry I made a mistake with the name, and your suggestion of `IndexSectionId` is better (since the DWO and DWP contain other sections that can't appear in the index).

2024-05-24 18:04 UTC, jameysharp commented
No problem; done. Almost everything I know about DWARF today is stuff I learned this week, so you could easily convince me either way. I'm always happy to take advice.

2024-05-25 03:53 UTC, philipc commented on src/read/index.rs
> +/// Section kinds which are permitted in a `.dwo` file.
```suggestion
/// Section kinds which are permitted in a `.dwp` index.
```

2024-05-25 04:07 UTC, philipc approved these changes

2024-05-25 04:09 UTC, merged

2024-05-25 08:02 UTC, philipc commented
Do you have plans for more gimli work? If not I'll do a release soon (along with object and addr2line).

2024-05-25 08:18 UTC, jameysharp commented
I don't have anything more planned right now. I kind of wanted to improve the string formatting of the `Error` type, both to include the data associated with the various `Unknown` and `Unsupported` variants, and also ideally to attach a `ReaderOffsetId` to every error, not just `UnexpectedEof`. But I don't think I actually have the energy for either of those projects at the moment.

I intend to dig into the support for DWARF that's in Wasmtime and Cranelift, so it's possible I'll find more things I'd like from gimli along the way. But for now, I think a new release would be great. Thanks for your help getting these changes merged so promptly!